name: Latest blog post workflow

on:
  schedule:
    # Runs every Monday at 08:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://letsautomate.it/index.xml"
          max_post_count: 5
          readme_path: "README.md"
          committer_username: "MSAdministrator"
          committer_email: "github-actions[bot]@users.noreply.github.com"
